export const projects = [
  {
    year: 2021,
    name: "shawn kelley developer",
    shortDesc: "My software engineering portfolio site.",
    description: [
      "A custom React / React Router v6 portfolio site with dynamic routing and data population as well as fully-implemented SASS.",
      "This project is highly accessible, with attention given to color contrast and markup heirarchy.",
    ],
    technologies: ["React", "React Router v6", "SASS"],
    live_link: "https://www.shawnkelley.dev",
    github_link: "https://github.com/shawnkelleydev/sk-ws-react",
    img: "../img/skd.png",
  },
  {
    year: 2021,
    name: "shawn kelley music",
    shortDesc: "A website for my work in music composition.",
    description: [
      "This website is the home of my other life in music composition and features React with React Router v6 and SASS.",
      "This project is highly accessible, with attention given to color contrast and markup heirarchy.",
    ],
    technologies: ["React", "React Router v6", "SASS"],
    live_link: "https://www.shawnkelleymusic.com",
    github_link: "https://github.com/shawnkelleydev/shawn_kelley_music",
    img: "../img/skm.png",
  },
  {
    year: 2021,
    name: "first light",
    shortDesc: "A simple way for Christians to start their day.",
    description: [
      "First Light is a React app designed to help Christians start their day.  It's super powered by numerous API integrations with NASA, Google, and Crossway.",
    ],
    tag: "First Light.  Find your way for the day.",
    technologies: ["React", "React Router v6", "Fetch API", "SASS"],
    live_link: "https://firstlight-skd.netlify.app",
    github_link: "https://github.com/shawnkelleydev/firstlight-fs",
    img: "../img/fl.png",
  },
  {
    year: 2021,
    name: "whitney kelley",
    shortDesc: "The internet home of flutist, Whitney Kelley.",
    description: [
      "Whitney Kelley is a professional flutist and teacher in the Denver metro area.  She's also my wife!",
      "Her website is full-stack and features a React/React Router v6 front end with dynamic content as well as a node/express back end for handling users and contact requests.",
      "Additionally, the project is highly accessible, with attention given to color contrast and markup heirarchy.",
      "Whitney's the best teacher I've ever known.  If you and yours need flute lessons, I encourage you to reach out to her.",
    ],
    technologies: ["React", "React Router v6", "Node", "Express", "CSS"],
    live_link: "https://www.whitneykelley.com",
    github_link: "https://github.com/shawnkelleydev/whitneykelley-fs",
    img: "../img/wk.png",
  },
  {
    year: 2021,
    name: "tomorrow land",
    shortDesc: "A full-stack budgeting app.",
    description: [
      "Tomorrow Land is a full-stack budgeting application.",
      "The project must be cloned on a local machine to work due to SQLite3 not playing well with Heroku.",
    ],
    tag: "Tomorrow Land.  Shape tomorrow today.",
    bugTitle: "Heroku and SQLite3",
    bugLink: "https://devcenter.heroku.com/articles/sqlite3",
    technologies: ["React", "Node", "Express", "ReST", "SQL", "CSS"],
    live_link: "https://keen-perlman-642ce0.netlify.app",
    github_link: "https://github.com/shawnkelleydev/tomorrow-land-fs",
    img: "../img/tl.png",
  },
  {
    year: 2022,
    name: "banderly",
    shortDesc: "A beginning band helper app.",
    description: [
      "Banderly is a simple beginning band assistant that takes advantage of browser MIDI technology.",
      "It helps teachers and students know which note should be coming out of each instrument and includes a pitch-selectable metronome.",
    ],
    tag: "Banderly.  Know thine instruments.",
    technologies: ["React", "CSS"],
    live_link: "https://www.banderly.com",
    github_link: "https://github.com/shawnkelleydev/banderly",
    img: "../img/banderly.png",
  },
  {
    year: 2021,
    name: "ToDoer",
    shortDesc: "A simple, vanilla JS task tracker.",
    description: [
      "ToDoer is an extremely simple vanilla JavaScript task tracker.",
      "It was a personal project and uses local storage to save user input between visits.",
    ],
    technologies: ["HTML", "CSS", "JavaScript"],
    live_link: "https://shawnkelleydev.github.io/ToDoer/",
    github_link: "https://github.com/shawnkelleydev/ToDoer",
    img: "../img/td.png",
  },
  {
    year: 2021,
    name: "Full Stack Course Library",
    shortDesc: "A Team Treehouse Techdegree Project.",
    description: [
      "A full-stack course library featuring user authentication.",
      "This was my final project from Team Treehouse.  Feel free to clone the project below and run on your local machine.",
    ],
    technologies: ["React", "Node", "Express", "ReST", "SQL"],
    github_link: "https://github.com/shawnkelleydev/techdegree-project-10-fs",
    // img: "../img/fscl.png",
  },
  {
    year: 2021,
    name: "SQL Library",
    shortDesc: "A Team Treehouse Techdegree Project.",
    description: [
      "An editable list of library books integrating JavaScript and SQL.",
      [
        "SQL Library was project from Team Treehouse, running on Heroku (please forgive sleepy Dyno delays).",
      ],
    ],
    technologies: ["Node", "Express", "SQL"],
    live_link: "https://intense-shore-26930.herokuapp.com/books",
    github_link: "https://github.com/shawnkelleydev/techdegree-project-8-sql",
    // img: "../img/sqll.png",
  },
  {
    year: 2021,
    name: "React Gallery",
    shortDesc: "A Team Treehouse Techdegree Project.",
    description: [
      "A React / React Router V5 integration with Flickr API.",
      "CSS for this project was provided by Team Treehouse.",
    ],
    technologies: ["React", "React Router V5", "Axios"],
    live_link: "https://gifted-payne-38443a.netlify.app",
    github_link: "https://github.com/shawnkelleydev/techdegree-project-7-react",
    // img: "../img/rg.png",
  },
  {
    year: 2021,
    name: "Express Portfolio",
    shortDesc: "A Team Treehouse Techdegree Project.",
    description: [
      "An Express / Pug portfolio project.  It's running on Heroku, so there may be a slight delay if the Dyno is sleeping.",
      "CSS for this project was provided by Team Treehouse.",
    ],
    technologies: ["Node", "Express", "Pug"],
    live_link: "https://sk-express-portfolio-tth.herokuapp.com",
    github_link: "https://github.com/shawnkelleydev/techdegree-project-7",
    // img: "../img/ep.png",
  },
  {
    year: 2021,
    name: "API employee directory",
    shortDesc: "A Team Treehouse Techdegree Project.",
    description: [
      "An API project with a gallery, search functionality, modals, and modal navigation.",
      "HTML and CSS for this project were provided by Team Treehouse.",
    ],
    technologies: ["JavaScript", "Fetch API"],
    live_link: "https://shawnkelleydev.github.io/techdegree-project-5/",
    github_link: "https://github.com/shawnkelleydev/techdegree-project-5",
    // img: "../img/apied.png",
  },

  {
    year: 2021,
    name: "OOP game",
    shortDesc: "A Team Treehouse Techdegree Project.",
    description: [
      "An OOP project in the form of a responsive phrase-hunting game with keyboard functionality.",
      "Phrase Hunter's CSS was provided by Team Treehouse and not designed to be mobile-friendly, so a wider-than-phone screen is recommended.",
    ],
    technologies: ["JavaScript", "OOP"],
    live_link: "https://shawnkelleydev.github.io/techdegree-project-4/",
    github_link: "https://github.com/shawnkelleydev/techdegree-project-4",
    // img: "../img/oop.png",
  },
  {
    year: 2021,
    name: "responsive form validation",
    shortDesc: "A Team Treehouse Techdegree Project.",
    description: [
      "This project demonstrates live form validation using regular expressions.  It also responsively prevents schedule conflicts.",
      "HTML and CSS for this project were provided by Team Treehouse.",
    ],
    technologies: ["JavaScript", "RegEx"],
    live_link: "https://shawnkelleydev.github.io/techdegree-project-3/",
    github_link: "https://github.com/shawnkelleydev/techdegree-project-3",
    // img: "../img/rfv.png",
  },
  {
    year: 2021,
    name: "student list pagination",
    shortDesc: "A Team Treehouse Techdegree Project.",
    description: [
      "This project demonstrates population, pagination, and search of a list of 42 students.",
      "HTML and CSS for this project were provided by Team Treehouse.",
    ],
    technologies: ["JavaScript"],
    live_link: "https://shawnkelleydev.github.io/techdegree-project-2/",
    github_link: "https://github.com/shawnkelleydev/techdegree-project-2",
    // img: "../img/slp.png",
  },
  {
    year: 2021,
    name: "random quotes",
    shortDesc: "A Team Treehouse Techdegree Project.",
    description: [
      "This project features JavaScript-selected quotes over a JavaScript-selected background color, refreshing every 7 seconds.",
      "HTML and CSS for this project were provided by Team Treehouse.",
    ],
    technologies: ["JavaScript"],
    live_link: "https://shawnkelleydev.github.io/techdegree-project-1/",
    github_link: "https://github.com/shawnkelleydev/techdegree-project-1",
    // img: "../img/rq.png",
  },
];

export const music = [
  {
    year: 2008,
    name: "urban suite",
    instrumentation: "eett",
    duration: "13",
    description:
      "A 2010 finalist for the ITEA Harvey Phillips Award, Urban Suite was fun to write and has been performed and recorded around the world.  It was completed in 2008, released in 2009, and premiered by faculty at Eastman School of Music.",
    video_link:
      "https://www.youtube.com/embed/videoseries?list=PL00ZKav_3htzX9Gj3mZIXVoHJda1q9h_5",
    purchase_link: "https://www.cimarronmusic.com/urban-suite-8504",
    audio_link: "https://open.spotify.com/album/4L6mJLsd5JhO3VD7pNVJZf",
    // img: "../img/us.png",
  },
  {
    year: 2020,
    name: "home suite home",
    instrumentation: "eett",
    duration: "10",
    description:
      "Completed in 2020 and released in 2021, Home Suite Home captures themes from daily life.",
    tag: "Available now from Cimarron Music Press.",
    purchase_link: "https://www.cimarronmusic.com/homesuitehome",
    // img: "../img/hsh.png",
  },
  {
    year: 2020,
    name: "an off day",
    instrumentation: "eett",
    duration: "6",
    description:
      "Completed in 2020 and released in 2021, An Off Day captures life as it so often is in a fun way.",
    tag: "Available now from Cimarron Music Press.",
    purchase_link: "https://www.cimarronmusic.com/anoffday",
    // img: "../img/aod.png",
  },
  {
    year: 2020,
    name: "the new school",
    instrumentation: "eett",
    description: "You're going.",
    tag: "Completed in 2020. Coming soon from Cimarron Music Press.",
    // img: "../img/tns.png",
  },
  {
    year: 2021,
    name: "china suite no. 1",
    instrumentation: "eett",
    description: "For my 中国朋友 (Chinese friend), Sòng Mǐn.",
    tag: "Completed in 2021. Coming soon from Cimarron Music Press.",
    // img: "../img/csn1.png",
  },
  {
    year: 2021,
    name: "i see",
    instrumentation: "eett",
    description: "Twas blind, but now...",
    tag: "Completed in 2021.  Coming soon from Cimarron Music Press.",
    // img: "../img/isee.png",
  },
  {
    year: 2021,
    name: "loud noises",
    instrumentation: "eett",
    description: "They're everywhere, after all.",
    tag: "Completed in 2021. Coming soon from Cimarron Music Press.",
    // img: "../img/ln.png",
  },
  {
    year: 2021,
    name: "spring",
    instrumentation: "eett",
    description: "A perspective on a beautiful season.",
    tag: "Completed in 2021. Coming soon from Cimarron Music Press.",
    // img: "../img/spring.png",
  },
  {
    year: 2021,
    name: "street songs",
    instrumentation: "eett",
    description: "for the wild, improvisation-loving tuba qudevet.",
    tag: "Completed in 2021. Coming soon from Cimarron Music Press.",
    // img: "../img/ss.png",
  },
];

export const all = projects.concat(music);
